version: '3.8'
services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
      - ./mysqllogs/:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=!fdhgrthfdhfdhfddrth54fdhgrthfdhfdhfddrth54y75u6j54!
    env_file:
      - nc.env
    networks:
      - net
    deploy:
      restart_policy:
        condition: on-failure
  app:
    image: nextcloud:apache
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./nextcloud/:/var/www/html
      - ./nextcloudLogs/:/var/log/apache2
    networks:
      - traefik-public
      - net
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.nextcloud-http.rule=Host(`next.otherrealm.org`)
        - traefik.http.routers.nextcloud-http.service=nextcloud
        - traefik.http.routers.nextcloud-http.entrypoints=http
        - traefik.http.routers.nextcloud-http.middlewares=https-redirect
        - traefik.http.routers.nextcloud-https.rule=Host(`next.otherrealm.org`)
        - traefik.http.routers.nextcloud-https.service=nextcloud
        - traefik.http.routers.nextcloud-https.entrypoints=https
        - traefik.http.routers.nextcloud-https.tls=true
        - traefik.http.routers.nextcloud-https.tls.certresolver=le
        - traefik.http.services.nextcloud.loadbalancer.server.port=80
        - traefik.http.middlewares.nextcloud-http2https.redirectscheme.scheme=https
        - traefik.http.middlewares.nextcloud-http2https.redirectscheme.permanent=true
        - traefik.http.routers.nextcloud-http.middlewares=nextcloud-http2https
    environment:
      - MYSQL_HOST=db
      - extra_params=--o:ssl.enable=false  
      - o:ssl.termination=true
    env_file:
      - nc.env
    depends_on:
      - db
volumes:
  db:
  nextcloud:
networks:
  net:
    driver: overlay
    attachable: true
  traefik-public:
    external: true