[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$k/zZXHjB$4dRuRhgUkA4thUlCBaewi0"
  ]

[http.routers.api]
  rule = "Host(`traefik.otherrealm.org`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"